apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-hello-world-preview
spec:
  generators:
    - pullRequest:
        github:
          owner: badaiv
          repo: docker-hello-world # (1)
#          tokenRef:
#            key: token
#            secretName: github-token # (2)
        requeueAfterSeconds: 15
  template:
    metadata:
      name: 'sample-hello-world-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        # (3)
        path: preview/
        repoURL: 'https://github.com/badaiv/kube-preview-env.git'
        targetRevision: HEAD
        helm:
          parameters:
            # (4)
            - name: namespace
              value: 'preview-{{branch}}'
            # (5)
            - name: version
              value: '{{head_sha}}'
            # (6)
            - name: image
              value: docker-hello-world
            - name: name
              value: docker-hello-world-preview
      # (7)
      syncPolicy:
        automated:
          selfHeal: true