apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: action
    - name: pull_request_id
    - name: repo_fullname
    - name: branch
    - name: sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pullrequest-pipeline-run-
      spec:
        pipelineRef:
          name: pipeline-hello-world
        params:
          - name: action
            value: "$(tt.params.action)"
          - name: pull_request_id
            value: "$(tt.params.pull_request_id)"
          - name: repo_fullname
            value: "$(tt.params.repo_fullname)"
          - name: branch
            value: "$(tt.params.branch)"
          - name: sha
            value: "$(tt.params.sha)"
        workspaces:
          - name: docker-credentials
            secret:
              secretName: docker-credentials
          - name: myworkspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 200Mi
